### ISSUE TITLE
pv3.VideoInterface composed of pv3.ImageMontage frames?

### ISSUE THREAD

**Issue by jfinken** [svohara/pyvision3#1]
Hypothetically speaking...say a former colleague was recently using pyvision3 (because it's great) to playback an image set previously collected with a high-frequency multi-camera system.  The camera system produces 2 or more images per _frameset_.  The colleague derived from `pv3.VideoInterface`, and implemented `__next__` via building up a `pyv3.ImageMontage` with each image per frameset.

To get it to `play(window_title=the_id, delay=delay, annotate=False, hack=True)`, he had to hack [video.py line 215](https://github.com/svohara/pyvision3/blob/master/pyvision3/video.py#L215) with essentially:

    if window_title is not None:
        if kwargs.get("hack", None) is None:
            img.show(window_title=window_title, highgui=True, pos=pos, delay=None, annotations_opacity=1.0)
        else:
            img.show(window_title=window_title, pos=pos, delay=None)

This works, but is there a proper `pyvision3`-esque way to go about this?  
Thanks!

**Comment by svohara** [comment]
Let me get back to you with a more thoughtful answer tomorrow. However, did you consider the video montage?

—Steve

**Comment by svohara** [comment]
Oh, and I’m stoked to hear from you! How’s quarantine life in Utah treating you?

—Steve

**Comment by jfinken** [comment]
Ah, video montage, I didn't see/consider it.  I'll take a look!  Thanks Steve.  We're doing well out here - lots of Google Classroom time, and some solid Settlers of Catan time (the Explorers and Pirates expansion is sweet).

Hope you're doing well out there!

**Comment by svohara** [comment]
@jfinken : can you provide a bit more context (i.e. code sample) to illustrate the issue? Seems like you shouldn't have to do anything to the play() method if your iterator returns a PV Image. Can you describe what the core problem is? Have you looked at creating the montage at each frame, then calling the `image_montage.as_image()` and returning that as the result of the iterator?

**Comment by svohara** [comment]
Also, not directly related to your issue, but for awareness. There are a few ways to do picture-in-picture type displays with pyvision3 beyond a single-level montage. For example, if you wanted to have a "main camera" displayed with the remaining cameras shown along the bottom as smaller insets. You can do a VideoMontage of [Video, VideoMontage], with a vertical layout. Or you could use the `image.annotate_inset_image()` method...the possibilities are endless! ;)

**Comment by jfinken** [comment]
> Have you looked at creating the montage at each frame, then calling the image_montage.as_image() and returning that as the result of the iterator?

Well that was the key!  Returning `imgmontage.as_image()` from the iterator now let's me do everything: playing and saving (!) the video, annotating each individual image in the montage, all without modifying pyv3.  I should have just RTFM.  And VideoMontage of [Video, VideoMontage] sounds cool too.  Thanks again Steve.

**Comment by svohara** [comment]
No problem. Glad I could help. Pyvision3 is due for some new features and some upgrading of the code (type hints at least). Let me know if you have specific needs/priorities, and obviously, I'm always open to pull requests. Closing this issue as resolved.
